name = "Nutrinfo"
uuid = "6a3345f1-16a6-41b5-a809-069af34afad7"
authors = ["Roger Mateer <rogermateer@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
